name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "5.0"
        include:
          - os: ubuntu-latest
            ocaml-compiler: "4.07"
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: setup
        run: |
          opam pin add . -y --no-action
          opam depext -y directories
          opam install -y ./*.opam --deps-only --with-test
          opam upgrade --fixup
      - name: build
        run: opam exec -- dune build @install
      - name: test
        run: |
          opam exec -- dune runtest
          opam exec -- dune build example/print_dir.exe
          opam exec -- dune exec example/print_dir.exe
